kind: Service
apiVersion: v1
metadata:
  name: mariadb
  namespace: "{{ virt_test_ns }}"
spec:
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
  selector:
    app: "{{ virt_vm_name }}"
