apiVersion: ocs.openshift.io/v1
kind: StorageCluster
metadata:
  namespace: openshift-storage
  name: ocs-storagecluster
spec:
  resources:
    mon:
      requests:
        cpu: '1'
        memory: 2Gi
    mds:
      requests:
        cpu: '3'
        memory: 8Gi
    mgr:
      requests:
        cpu: '1'
        memory: 3Gi
    noobaa-core:
      requests:
        cpu: '1'
        memory: 4Gi
    noobaa-db:
      requests:
        cpu: '1'
        memory: 4Gi
  storageDeviceSets:
  - name: ocs-deviceset
    config: {}
    count: 1
    replica: 3
    resources:
      requests:
        cpu: '2'
        memory: 5Gi
    placement: {}
    preparePlacement: {}
    dataPVCTemplate:
      metadata: {}
      spec:
        storageClassName: gp3-csi
        accessModes:
        - ReadWriteOnce
        volumeMode: Block
        resources:
          requests:
            storage: 2Ti
      status: {}
    portable: true

