---
apiVersion: v1
kind: Namespace
metadata:
  name: "{{ ceph_ns }}"
spec:
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: odf-operator
  namespace: "{{ ceph_ns }}"
spec:
  installPlanApproval: Automatic
  name: odf-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: odf-operator
  namespace: "{{ ceph_ns }}"
spec:
  targetNamespaces:
    - "{{ ceph_ns }}"
  upgradeStrategy: Default
