apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: {{ operator_name }}
  namespace: {{ operator_namespace }}
spec:
  channel: {{ operator_channel }}
  installPlanApproval: Automatic
  name: {{ operator_name }}
  source: test-fusion-access-operator
  sourceNamespace: openshift-marketplace
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: fusion-access-operator-group
  namespace: {{ operator_namespace }}
spec:
  upgradeStrategy: Default
