apiVersion: core.libopenstorage.org/v1
kind: StorageCluster
metadata:
  name: portworx
  annotations:
    portworx.io/is-openshift: 'true'
  namespace: openshift-operators
spec:
  deleteStrategy:
    type: UninstallAndWipe
  storage:
    devices:
      - {{ realdevice }}
