---
apiVersion: v1
kind: Namespace
metadata:
  name: ibm-test-deployment
spec:
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ibm-scale-claim
  namespace: ibm-test-deployment
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: "localfilesystem"
  resources:
    requests:
      storage: 200Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: writer
  name: writer
  namespace: ibm-test-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: writer
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: writer
    spec:
      volumes:
      - name: shared-volume
        persistentVolumeClaim:
          claimName: ibm-scale-claim
      containers:
      - name: writer
        image: alpine
        command: ["/bin/sh", "-c", "while true; do echo $(date) >> /mnt/date.txt; sleep 1; done"]
        volumeMounts:
          - name: shared-volume
            mountPath: "/mnt"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: reader
  name: reader
  namespace: ibm-test-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reader
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: reader
    spec:
      volumes:
      - name: shared-volume
        persistentVolumeClaim:
          claimName: ibm-scale-claim
      containers:
      - name: reader
        image: alpine
        command: ["/bin/sh", "-c", "while true; do cat /mnt/date.txt; sleep 1; done"]
        volumeMounts:
          - name: shared-volume
            mountPath: "/mnt"
