---
apiVersion: v1
kind: Namespace
metadata:
  name: openshift-cnv
spec:
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: kubevirt-hyperconverged
  namespace: openshift-cnv
spec:
  channel: stable
  installPlanApproval: Automatic
  name: kubevirt-hyperconverged
  source: redhat-operators
  sourceNamespace: openshift-marketplace
{% if kvm_emulation %}
  config:
    env:
    - name: KVM_EMULATION
      value: "true"
{% endif %}
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: cnv-operator
  namespace: openshift-cnv
spec:
  upgradeStrategy: Default
  targetNamespaces:
    - openshift-cnv
